export const SUPABASE = {
  BUCKET_MANGA: {
    NAME: process.env.NEXT_PUBLIC_SUPABASE_BUCKET_MANGA_NAME || "bucket",
    EXPIRES_IN: Number(process.env.NEXT_PUBLIC_SUPABASE_BUCKET_SIGNED_URL_EXPIRES_IN) || 3600,
    PUBLIC_LOADER_URL: process.env.NEXT_PUBLIC_SUPABASE_PUBLIC_LOADER_URL,
    IMAGE: {
      QUALITY: 50,
      WIDTH: 200,
    },
  },
};
